### ISSUE TITLE
Meaning of the penalize_unk flag

### ISSUE THREAD

**Issue by ajaech** [neubig/modlm#4]
I'm trying to figure out how <unk>'s are handled during training and evaluation. There is a flag called "penalize_unk" that can be set to true or false. If it is true then I expect <unk>s to be treated the same as any word in the vocabulary. If it is false then I expect the <unk>'s to be ignored during training and testing. 

The first issue is that there is no way to remove unk's from the n-gram models. This means that these will always assign probability mass to the unk token even when we are telling it that there are no unk's in the test data.

The second issue is that when the penalize_unk flag is false, the way the average log likelihood seems to be calculated is to not include <unk> in the numerator but to still include it in the denominator. If there are a lot of unks then the perplexity becomes really low. What I would expect is that the unk's should not be counted in both the numerator and the denominator. I'm pretty sure this is what SRILM does. This behavior is non-intuitive and makes me wonder why the penalize_unk flag is set to false in the example script.

I'm still working on understanding all the code. If I can figure it out myself I will try and submit a fix myself.

**Comment by neubig** [comment]
The meaning of ``--penalize_unk`` requires thinking about what the "&lt;unk&gt;" token means.
Let's say we have "this is modlm", where modlm is not in the vocabulary. This means that a language modeling toolkit will calculate:
* P(this) P(is | this) P(&lt;unk&gt; | this, is) P(&lt;/s&gt; | this is &lt;unk&gt;)

This is the default `modlm` behavior without the `--penalize_unk` flag, and the default in SRILM and many other toolkits.

However, the word "modlm" has disappeared from this equation, right? Let's say we had another sentence "this is modlm-train" where "modlm-train" was also an &lt;unk&gt;. This would also be assigned the same probability as the sentence above, and given that we have a large number of unknown words, there's a good chance that the sum of the probabilities could go over 1, which is a problem in probability land. 

In order to actually assign probability to the original sentence "this is modlm", we actually need to have something like
* P(this) P(is | this) P(&lt;unk&gt; | this, is) P_{unk}(modlm) P(&lt;/s&gt; | this is &lt;unk&gt;)

where "P_{unk}()" is a separate probability distribution that calculates the probability of "modlm" given that it is an unk. This is done in many ways, for example using character-by-character models that predict the surface form of the word character-by-character. My language modeling tutorial slides here cover this a bit: https://phontron.com/teaching.php

However, this is a bit annoying, because you need to create a separate character-based language model exclusively for &lt;unk&gt; tokens. The `--penalize_unk` option is a compromise, which assumes that "P_{unk}(x) == 1/|V|" where "|V|" is the size of the *known* words in the vocabulary. This is making the assumption that the number of possible unknown words is equal to the number of known words in the vocabulary. This is obviously wrong (there will almost always be more unknown word types than known word types), but it's better than nothing. I believe I first saw this idea in kenlm, and copied the idea from there.

A practical consequence of setting this flag is that except in very degenerate cases (e.g. making *all* of your words in the training data &lt;unk&gt;), this will give you a big penalty when you get a data set with lots of &lt;unk&gt; words, causing the perplexity to be worse than a data set where most of the words are in vocabulary. This is a good thing, because a data set with lots of unknown words will usually be harder to process, and the perplexity being worse reflects this, where if you set the `--penalize_unk` flag to false, there's a good chance that the perplexity will be better because the &lt;unk&gt; token is assigned a high probability.

Hope this helps!

**Comment by ajaech** [comment]
Thanks for your response. I understand your motivations now. 

I'm coming at this from a speech recognition perspective where there are no unks at test time. It is not possible for the recognizer to produce a word that is not in the vocabulary. Since SRILM was built by speech people then they handle this in the right way for working with speech data.

**Comment by neubig** [comment]
Gotcha. But "no unks at test time" actually means "we fail to recognize unks at test time because we can't handle them", right? So if you use the `--penalize_unk` flag, perplexities will be more highly correlated with test-time WERs because you'll get a penalty in both perplexity and WER when you see an unk.

**Comment by ajaech** [comment]
Thanks. I'm going to work on doing a fork that does what I need. To compare with other LMs for speech recognition it's important that the model doesn't assign any probability mass to unk.

**Comment by neubig** [comment]
Sure, for the purpose of experiments that's the right thing to do of course.

**Comment by honnibal** [comment]
Btw if you want a nicer way to smooth unigram distributions, I've found Simple Good-Turing to perform the best: https://pdfs.semanticscholar.org/3c0f/046634f8102c2acb495aaf7f14924c2d4ee7.pdf

There's a bug in most descriptions of this though: the algorithm gives an estimate of the total mass assigned to OOV words, but what we want is to know how much mass to assign to *each* OOV word. This requires a count of the number of OOV words, which is obviously unavailable.

The paper's description is unclear about this, and the lack of clarity as inherited by Manning's book, and also the CoreNLP implementation. CoreNLP calculates a *higher* probability for OOV words than happax words -- which is plainly crazy! https://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/stats/SimpleGoodTuring.html

I've had success with estimating the number of zeros by extrapolating from the number of 1s and the number of 2s: `Nr0 = Nr1 + (Nr1 - Nr2)`. This gives a pretty good unigram distribution. My SGT code can be found here if you're curious: https://github.com/explosion/preshed/blob/master/preshed/counter.pyx

**Comment by neubig** [comment]
@honnibal I like the idea of extrapolating the number of words! It'd probably be even more accurate if you took into the account the Zipfian distribution somehow.
